version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_pay_api
    ports:
      - "3000:3001"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:prod